//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientManagement.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatientManagementDBEntities : DbContext
    {
        public PatientManagementDBEntities()
            : base("name=PatientManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblPatient> tblPatient { get; set; }
        public virtual DbSet<tblPatienttest> tblPatienttest { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
    }
}
