//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientManagement.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phonenumber { get; set; }
        public string Gender { get; set; }
        public string Countryid { get; set; }
        public string Patientid { get; set; }
    }
}
